// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtmz9iitkQegzvxoJ3ubT2uOr7CpUDCd8',
    appId: '1:590050868894:web:378edcfc83d1f2591f858f',
    messagingSenderId: '590050868894',
    projectId: 'bazar-63c93',
    authDomain: 'bazar-63c93.firebaseapp.com',
    storageBucket: 'bazar-63c93.firebasestorage.app',
    measurementId: 'G-Q1GHRWMEL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAORKJVM2nINl3CLa2EYAF7wsiaJxfJNAU',
    appId: '1:590050868894:android:7a40e375606521951f858f',
    messagingSenderId: '590050868894',
    projectId: 'bazar-63c93',
    storageBucket: 'bazar-63c93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSBDA8uWq4H54FsL-Bl4GjJufU5dmGxl8',
    appId: '1:590050868894:ios:838e405bbf7922791f858f',
    messagingSenderId: '590050868894',
    projectId: 'bazar-63c93',
    storageBucket: 'bazar-63c93.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSBDA8uWq4H54FsL-Bl4GjJufU5dmGxl8',
    appId: '1:590050868894:ios:838e405bbf7922791f858f',
    messagingSenderId: '590050868894',
    projectId: 'bazar-63c93',
    storageBucket: 'bazar-63c93.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtmz9iitkQegzvxoJ3ubT2uOr7CpUDCd8',
    appId: '1:590050868894:web:3d1b1bc9505b9bc11f858f',
    messagingSenderId: '590050868894',
    projectId: 'bazar-63c93',
    authDomain: 'bazar-63c93.firebaseapp.com',
    storageBucket: 'bazar-63c93.firebasestorage.app',
    measurementId: 'G-YZKPSNDFTV',
  );
}
